import { Product } from "./types";

export const mangalsutras: Product[] = [
  {
    id: "m-01",
    name: "Ruby Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_1.png",
    images: ["/images/products/mangalsutra/mangalsutra_1.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 42000,
    slug: "ruby-mangalsutra",
    sku: "RJMS0001",
    netWeight: 11,
    goldRate: 6500,
    makingCharges: 3000,
    stoneCharges: 5000,
    avgRating: 4.7,
    reviewCount: 22,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-02",
    name: "EternalSpark Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_2.png",
    images: ["/images/products/mangalsutra/mangalsutra_2.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 67800,
    slug: "eternalspark-gold-mangalsutra",
    sku: "RJMS0002",
    netWeight: 7.4,
    goldRate: 6500,
    makingCharges: 1500,
    stoneCharges: 0,
    avgRating: 4.9,
    reviewCount: 176,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-03",
    name: "Classic Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_3.png",
    images: ["/images/products/mangalsutra/mangalsutra_3.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 48500,
    slug: "classic-gold-mangalsutra",
    sku: "RJMS0003",
    netWeight: 8.2,
    goldRate: 6500,
    makingCharges: 2200,
    stoneCharges: 500,
    avgRating: 4.6,
    reviewCount: 34,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-04",
    name: "Elegant Pearl Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_4.png",
    images: ["/images/products/mangalsutra/mangalsutra_4.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 52900,
    slug: "elegant-pearl-mangalsutra",
    sku: "RJMS0004",
    netWeight: 8.8,
    goldRate: 6500,
    makingCharges: 2400,
    stoneCharges: 1200,
    avgRating: 4.8,
    reviewCount: 48,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-05",
    name: "Royal Bead Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_5.png",
    images: ["/images/products/mangalsutra/mangalsutra_5.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 61500,
    slug: "royal-bead-mangalsutra",
    sku: "RJMS0005",
    netWeight: 9.6,
    goldRate: 6500,
    makingCharges: 2800,
    stoneCharges: 1800,
    avgRating: 4.7,
    reviewCount: 61,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-06",
    name: "Modern Charm Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_6.png",
    images: ["/images/products/mangalsutra/mangalsutra_6.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 45200,
    slug: "modern-charm-mangalsutra",
    sku: "RJMS0006",
    netWeight: 7.1,
    goldRate: 6500,
    makingCharges: 1900,
    stoneCharges: 800,
    avgRating: 4.5,
    reviewCount: 29,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-07",
    name: "Divine Drop Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_7.png",
    images: ["/images/products/mangalsutra/mangalsutra_7.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 57500,
    slug: "divine-drop-mangalsutra",
    sku: "RJMS0007",
    netWeight: 8.9,
    goldRate: 6500,
    makingCharges: 2600,
    stoneCharges: 1500,
    avgRating: 4.8,
    reviewCount: 73,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-08",
    name: "Traditional Lakshmi Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_8.png",
    images: ["/images/products/mangalsutra/mangalsutra_8.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 73500,
    slug: "traditional-lakshmi-mangalsutra",
    sku: "RJMS0008",
    netWeight: 11.2,
    goldRate: 6500,
    makingCharges: 3200,
    stoneCharges: 2400,
    avgRating: 4.9,
    reviewCount: 112,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-09",
    name: "Black Bead Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_9.png",
    images: ["/images/products/mangalsutra/mangalsutra_9.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 49800,
    slug: "black-bead-gold-mangalsutra",
    sku: "RJMS0009",
    netWeight: 7.8,
    goldRate: 6500,
    makingCharges: 2100,
    stoneCharges: 600,
    avgRating: 4.6,
    reviewCount: 37,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-10",
    name: "Royal Heritage Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_10.png",
    images: ["/images/products/mangalsutra/mangalsutra_10.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 82500,
    slug: "royal-heritage-mangalsutra",
    sku: "RJMS0010",
    netWeight: 12.6,
    goldRate: 6500,
    makingCharges: 3600,
    stoneCharges: 3000,
    avgRating: 4.9,
    reviewCount: 94,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-11",
    name: "Minimal Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_11.png",
    images: ["/images/products/mangalsutra/mangalsutra_11.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 38900,
    slug: "minimal-gold-mangalsutra",
    sku: "RJMS0011",
    netWeight: 6.3,
    goldRate: 6500,
    makingCharges: 1600,
    stoneCharges: 0,
    avgRating: 4.5,
    reviewCount: 18,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-12",
    name: "Lotus Design Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_12.png",
    images: ["/images/products/mangalsutra/mangalsutra_12.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 56400,
    slug: "lotus-design-mangalsutra",
    sku: "RJMS0012",
    netWeight: 8.5,
    goldRate: 6500,
    makingCharges: 2500,
    stoneCharges: 1300,
    avgRating: 4.8,
    reviewCount: 55,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-13",
    name: "Diamond Look Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_13.png",
    images: ["/images/products/mangalsutra/mangalsutra_13.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 69200,
    slug: "diamond-look-mangalsutra",
    sku: "RJMS0013",
    netWeight: 8.1,
    goldRate: 6500,
    makingCharges: 2900,
    stoneCharges: 2200,
    avgRating: 4.7,
    reviewCount: 82,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-14",
    name: "Elegant Curve Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_14.png",
    images: ["/images/products/mangalsutra/mangalsutra_14.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 47800,
    slug: "elegant-curve-mangalsutra",
    sku: "RJMS0014",
    netWeight: 7.2,
    goldRate: 6500,
    makingCharges: 2000,
    stoneCharges: 700,
    avgRating: 4.6,
    reviewCount: 31,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-15",
    name: "Classic Pendant Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_15.png",
    images: ["/images/products/mangalsutra/mangalsutra_15.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 59800,
    slug: "classic-pendant-mangalsutra",
    sku: "RJMS0015",
    netWeight: 9.1,
    goldRate: 6500,
    makingCharges: 2700,
    stoneCharges: 1100,
    avgRating: 4.8,
    reviewCount: 67,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-16",
    name: "Suhana Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_16.png",
    images: ["/images/products/mangalsutra/mangalsutra_16.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 51200,
    slug: "suhana-gold-mangalsutra",
    sku: "RJMS0016",
    netWeight: 7.9,
    goldRate: 6500,
    makingCharges: 2300,
    stoneCharges: 900,
    avgRating: 4.7,
    reviewCount: 44,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-17",
    name: "Aarohi Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_17.png",
    images: ["/images/products/mangalsutra/mangalsutra_17.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 64100,
    slug: "aarohi-mangalsutra",
    sku: "RJMS0017",
    netWeight: 9.8,
    goldRate: 6500,
    makingCharges: 2800,
    stoneCharges: 1700,
    avgRating: 4.9,
    reviewCount: 103,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-18",
    name: "Golden Petal Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_18.png",
    images: ["/images/products/mangalsutra/mangalsutra_18.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 55300,
    slug: "golden-petal-mangalsutra",
    sku: "RJMS0018",
    netWeight: 8.4,
    goldRate: 6500,
    makingCharges: 2400,
    stoneCharges: 1000,
    avgRating: 4.7,
    reviewCount: 52,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-19",
    name: "Maharani Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_19.png",
    images: ["/images/products/mangalsutra/mangalsutra_19.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 89500,
    slug: "maharani-mangalsutra",
    sku: "RJMS0019",
    netWeight: 13.4,
    goldRate: 6500,
    makingCharges: 3900,
    stoneCharges: 3500,
    avgRating: 4.9,
    reviewCount: 126,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-20",
    name: "Daily Wear Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_20.png",
    images: ["/images/products/mangalsutra/mangalsutra_20.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 36500,
    slug: "daily-wear-mangalsutra",
    sku: "RJMS0020",
    netWeight: 5.9,
    goldRate: 6500,
    makingCharges: 1500,
    stoneCharges: 0,
    avgRating: 4.5,
    reviewCount: 21,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-21",
    name: "Sanskriti Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_21.png",
    images: ["/images/products/mangalsutra/mangalsutra_21.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 61500,
    slug: "sanskriti-mangalsutra",
    sku: "RJMS0021",
    netWeight: 9.3,
    goldRate: 6500,
    makingCharges: 2700,
    stoneCharges: 1200,
    avgRating: 4.8,
    reviewCount: 71,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-22",
    name: "Aadhya Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_22.png",
    images: ["/images/products/mangalsutra/mangalsutra_22.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 58200,
    slug: "aadhya-mangalsutra",
    sku: "RJMS0022",
    netWeight: 8.7,
    goldRate: 6500,
    makingCharges: 2500,
    stoneCharges: 900,
    avgRating: 4.7,
    reviewCount: 46,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-23",
    name: "Shimmer Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_23.png",
    images: ["/images/products/mangalsutra/mangalsutra_23.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 64800,
    slug: "shimmer-gold-mangalsutra",
    sku: "RJMS0023",
    netWeight: 9.5,
    goldRate: 6500,
    makingCharges: 2800,
    stoneCharges: 1400,
    avgRating: 4.8,
    reviewCount: 89,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-24",
    name: "Graceful Bead Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_24.png",
    images: ["/images/products/mangalsutra/mangalsutra_24.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 47500,
    slug: "graceful-bead-mangalsutra",
    sku: "RJMS0024",
    netWeight: 7.3,
    goldRate: 6500,
    makingCharges: 1900,
    stoneCharges: 500,
    avgRating: 4.6,
    reviewCount: 36,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-25",
    name: "Premium Designer Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_25.png",
    images: ["/images/products/mangalsutra/mangalsutra_25.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 78500,
    slug: "premium-designer-mangalsutra",
    sku: "RJMS0025",
    netWeight: 11.7,
    goldRate: 6500,
    makingCharges: 3400,
    stoneCharges: 2800,
    avgRating: 4.9,
    reviewCount: 118,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-26",
    name: "Simple Elegance Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_26.png",
    images: ["/images/products/mangalsutra/mangalsutra_26.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 41500,
    slug: "simple-elegance-mangalsutra",
    sku: "RJMS0026",
    netWeight: 6.8,
    goldRate: 6500,
    makingCharges: 1800,
    stoneCharges: 300,
    avgRating: 4.5,
    reviewCount: 24,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-27",
    name: "Kundan Style Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_27.png",
    images: ["/images/products/mangalsutra/mangalsutra_27.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 72500,
    slug: "kundan-style-mangalsutra",
    sku: "RJMS0027",
    netWeight: 10.2,
    goldRate: 6500,
    makingCharges: 3200,
    stoneCharges: 2600,
    avgRating: 4.8,
    reviewCount: 76,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "m-28",
    name: "Royal Black Bead Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_28.png",
    images: ["/images/products/mangalsutra/mangalsutra_28.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 53200,
    slug: "royal-black-bead-mangalsutra",
    sku: "RJMS0028",
    netWeight: 8.3,
    goldRate: 6500,
    makingCharges: 2300,
    stoneCharges: 800,
    avgRating: 4.7,
    reviewCount: 43,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-29",
    name: "Festive Glow Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_29.png",
    images: ["/images/products/mangalsutra/mangalsutra_29.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 68900,
    slug: "festive-glow-mangalsutra",
    sku: "RJMS0029",
    netWeight: 9.7,
    goldRate: 6500,
    makingCharges: 2900,
    stoneCharges: 1900,
    avgRating: 4.9,
    reviewCount: 97,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-30",
    name: "Elegant Leaf Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_30.png",
    images: ["/images/products/mangalsutra/mangalsutra_30.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 55800,
    slug: "elegant-leaf-mangalsutra",
    sku: "RJMS0030",
    netWeight: 8.1,
    goldRate: 6500,
    makingCharges: 2400,
    stoneCharges: 700,
    avgRating: 4.6,
    reviewCount: 39,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },

  {
    id: "m-31",
    name: "Bridal Royal Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_31.png",
    images: ["/images/products/mangalsutra/mangalsutra_31.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 92500,
    slug: "bridal-royal-mangalsutra",
    sku: "RJMS0031",
    netWeight: 14.2,
    goldRate: 6500,
    makingCharges: 4200,
    stoneCharges: 3800,
    avgRating: 4.9,
    reviewCount: 143,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "m-32",
    name: "Contemporary Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_32.png",
    images: ["/images/products/mangalsutra/mangalsutra_32.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 49500,
    slug: "contemporary-mangalsutra",
    sku: "RJMS0032",
    netWeight: 7.6,
    goldRate: 6500,
    makingCharges: 2100,
    stoneCharges: 600,
    avgRating: 4.7,
    reviewCount: 33,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },

  {
    id: "m-33",
    name: "Signature Gold Mangalsutra",
    image: "/images/products/mangalsutra/mangalsutra_33.png",
    images: ["/images/products/mangalsutra/mangalsutra_33.png"],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 74800,
    slug: "signature-gold-mangalsutra",
    sku: "RJMS0033",
    netWeight: 10.8,
    goldRate: 6500,
    makingCharges: 3300,
    stoneCharges: 2300,
    avgRating: 4.9,
    reviewCount: 121,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
];