import { Product } from "./types";

export const necklaces: Product[] = [
  {
    id: "p-1",
    name: "Antique Polki Necklace",
    image: "/images/products/necklaces/gold-necklace-1.png",

    images: ["/images/products/necklaces/gold-necklace-1.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 25000,
    slug: "antique-polki-necklace",
    sku: "RJ-NCK-001",
    netWeight: 9.8,
    goldRate: 6500,
    makingCharges: 2500,
    stoneCharges: 4000,
    avgRating: 4.5,
    reviewCount: 12,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
    {
    id: "p-2",
    name: "Signature Heritage Necklace",
    image: "/images/products/necklaces/gold-necklace-14.png",

    images: ["/images/products/necklaces/gold-necklace-14.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "signature-heritage-necklace",
    sku: "RJ-NCK-002",
    netWeight: 17.29,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },


    {
    id: "p-3",
    name: "Royal Craft Necklace",
    image: "/images/products/necklaces/gold-necklace-15.png",

    images: ["/images/products/necklaces/gold-necklace-15.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "royal-craft-necklace",
    sku: "RJ-NCK-003",
    netWeight: 14.8,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

  {
    id: "p-4",
    name: "Diamond Tennis Necklaces",
    image: "/images/products/necklaces/gold-necklace-2.png",

    images: ["/images/products/necklaces/gold-necklace-2.png"],
    metal: "Diamond",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 78000,
    slug: "diamond-tennis-bracelet",
    sku: "RJ-NCK-004",
    netWeight: 9.82,
    goldRate: 6500,
    makingCharges: 4000,
    stoneCharges: 20000,
    avgRating: 4.9,
    reviewCount: 35,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

    {
    id: "p-5",
    name: "Antique Necklace Set",
    image: "/images/products/necklaces/gold-necklace-36.png",

    images: ["/images/products/necklaces/gold-necklace-36.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "antique-coin-necklace",
    sku: "RJ-NCK-005",
    netWeight: 13.61,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-6",
    name: "American Diamond Necklace Set",
    image: "/images/products/necklaces/gold-necklace-3.png",

    images: ["/images/products/necklaces/gold-necklace-3.png"],
    metal: "gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 54000,
    slug: "american-diamond-necklace-set",
    sku: "RJ-NCK-006",
    netWeight: 9.53,
    goldRate: 6500,
    makingCharges: 4500,
    stoneCharges: 15000,
    avgRating: 4.8,
    reviewCount: 28,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-7",
    name: "Temple Lakshmi Haram Necklace Set",
    image: "/images/products/necklaces/gold-necklace-4.png",

    images: ["/images/products/necklaces/gold-necklace-4.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 185000,
    slug: "temple-lakshmi-haram-necklace-set",
    sku: "RJ-NCK-007",
    netWeight: 10.35,
    goldRate: 6500,
    makingCharges: 22000,
    stoneCharges: 0,
    avgRating: 4.9,
    reviewCount: 64,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-8",
    name: "Antique Temple Long Necklace Set",
    image: "/images/products/necklaces/gold-necklace-5.png",

    images: ["/images/products/necklaces/gold-necklace-5.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 128000,
    slug: "antique-temple-long-necklace-set",
    sku: "RJ-NCK-008",
    netWeight: 8.8,
    goldRate: 6500,
    makingCharges: 16500,
    stoneCharges: 0,
    avgRating: 4.7,
    reviewCount: 39,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-9",
    name: "Traditional Lakshmi Coin Haram Set",
    image: "/images/products/necklaces/gold-necklace-6.png",

    images: ["/images/products/necklaces/gold-necklace-6.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 154000,
    slug: "traditional-lakshmi-coin-haram-set",
    sku: "RJ-NCK-009",
    netWeight: 9.8,
    goldRate: 6500,
    makingCharges: 18500,
    stoneCharges: 3500,
    avgRating: 4.8,
    reviewCount: 52,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-10",
    name: "Bridal Temple Layered Necklace Set",
    image: "/images/products/necklaces/gold-necklace-7.png",

    images: ["/images/products/necklaces/gold-necklace-7.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 245000,
    slug: "bridal-temple-layered-necklace-set",
    sku: "RJ-NCK-010",
    netWeight: 7.05,
    goldRate: 6500,
    makingCharges: 28000,
    stoneCharges: 8000,
    avgRating: 5.0,
    reviewCount: 71,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "p-11",
    name: "Antique Gold Drop Necklace",
    image: "/images/products/necklaces/gold-necklace-8.png",

    images: ["/images/products/necklaces/gold-necklace-8.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "22K",
    currentPrice: 48500,
    slug: "antique-gold-drop-necklace",
    sku: "RJ-NCK-011",
    netWeight: 7.71,
    goldRate: 6500,
    makingCharges: 5200,
    stoneCharges: 1800,
    avgRating: 4.8,
    reviewCount: 29,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-12",
    name: "Modern Diamond Curve Necklace Set",
    image: "/images/products/necklaces/gold-necklace-9.png",

    images: ["/images/products/necklaces/gold-necklace-9.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 64500,
    slug: "modern-diamond-curve-necklace-set",
    sku: "RJ-NCK-012",
    netWeight: 6.78,
    goldRate: 6500,
    makingCharges: 7200,
    stoneCharges: 14500,
    avgRating: 4.8,
    reviewCount: 33,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-13",
    name: "Aqua Stone Designer Necklace Set",
    image: "/images/products/necklaces/gold-necklace-10.png",

    images: ["/images/products/necklaces/gold-necklace-10.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 88500,
    slug: "aqua-stone-designer-necklace-set",
    sku: "RJ-NCK-013",
    netWeight: 7.25,
    goldRate: 6500,
    makingCharges: 9800,
    stoneCharges: 22000,
    avgRating: 4.9,
    reviewCount: 41,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-14",
    name: "Floral Pearl Diamond Necklace Set",
    image: "/images/products/necklaces/gold-necklace-11.png",

    images: ["/images/products/necklaces/gold-necklace-11.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "floral-pearl-diamond-necklace-set",
    sku: "RJ-NCK-014",
    netWeight: 10.28,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },

   {
    id: "p-15",
    name: "Classic Maharani Necklace",
    image: "/images/products/necklaces/gold-necklace-39.png",

    images: ["/images/products/necklaces/gold-necklace-39.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "classic-maharani-necklace",
    sku: "RJ-NCK-015",
    netWeight: 16.15,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },



  {
    id: "p-16",
    name: "Vanya Flow  Necklace",
    slug: "vanya-flow-necklace",
    sku: "RJ-NCK-016",
    image: "/images/products/necklaces/gold-necklace-16.png",

    images: ["/images/products/necklaces/gold-necklace-16.png"],
    metal: "Gold",
    purity: "18KT",
    netWeight: 14.74,
    currentPrice: 124000,
    goldRate: 6500,
    makingCharges: 2500,
    stoneCharges: 18000,
    avgRating: 4.9,
    reviewCount: 58,
    inStock: true,
    isFeatured: true,
    isTrending: true,
    category: "Necklaces",
  },
  {
    id: "p-17",
    name: "Emerald Bloom Gold Necklace Set",

    image: "/images/products/necklaces/gold-necklace-12.png",

    images: ["/images/products/necklaces/gold-necklace-12.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug:"emerald-bloom-gold-necklace",
    sku: "RJ-NCK-017",
    netWeight: 10.42,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-18",
    name: "Royal Pearl Elegance Necklace",
    image: "/images/products/necklaces/gold-necklace-13.png",

    images: ["/images/products/necklaces/gold-necklace-13.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "royal-pearl-elegance-necklace",
    sku: "RJ-NCK-018",
    netWeight: 9.34,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-19",
    name: "Heritage Bridal Gold Necklace",
    image: "/images/products/necklaces/gold-necklace-38.png",

    images: ["/images/products/necklaces/gold-necklace-38.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "heritage-bridal-gold-necklace",
    sku: "RJ-NCK-019",
    netWeight: 12.31,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-20",
    name: "Radiance Gold Necklace",
    image: "/images/products/necklaces/gold-necklace-37.png",

    images: ["/images/products/necklaces/gold-necklace-37.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "radience-gold-necklace",
    sku: "RJ-NCK-020",
    netWeight: 11.14,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-21",
    name: " Necklace Set",
    image: "/images/products/necklaces/gold-necklace-17.png",

    images: ["/images/products/necklaces/gold-necklace-17.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "vintage-necklace-set",
    sku: "RJ-NCK-021",
    netWeight: 16.16,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-22",
    name: "Antique Floral Necklace Set",
    image: "/images/products/necklaces/gold-necklace-18.png",

    images: ["/images/products/necklaces/gold-necklace-18.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "antique-floral-necklace-set",
    sku: "RJ-NCK-022",
    netWeight: 15.22,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-23",
    name: " Heritage Gold Necklace Set",
    image: "/images/products/necklaces/gold-necklace-19.png",

    images: ["/images/products/necklaces/gold-necklace-19.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "heritage-gold-necklace-set",
    sku: "RJ-NCK-023",
    netWeight: 9.98,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-24",
    name: "Maharani Pendant Necklace",
    image: "/images/products/necklaces/gold-necklace-20.png",

    images: ["/images/products/necklaces/gold-necklace-20.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "maharani-pendant-necklace",
    sku: "RJ-NCK-024",
    netWeight: 9.67,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-25",
    name: "Temple Heritage Necklace",
    image: "/images/products/necklaces/gold-necklace-21.png",

    images: ["/images/products/necklaces/gold-necklace-21.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "temple-heritage-necklace",
    sku: "RJ-NCK-025",
    netWeight: 10.61,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-26",
    name: "Regal Blossom Necklace",
    image: "/images/products/necklaces/gold-necklace-22.png",

    images: ["/images/products/necklaces/gold-necklace-22.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "regal-blossom-necklace",
    sku: "RJ-NCK-026",
    netWeight: 9.41,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-27",
    name: "Classic Gold Pendant Set",
    image: "/images/products/necklaces/gold-necklace-23.png",

    images: ["/images/products/necklaces/gold-necklace-23.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "classic-gold-pendant-set",
    sku: "RJ-NCK-027",
    netWeight: 9.44,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-28",
    name: "royal peacock necklace",
    image: "/images/products/necklaces/gold-necklace-24.png",

    images: ["/images/products/necklaces/gold-necklace-24.png"],
    metal: "Gold",
    category: "necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "royal-peacock-necklace",
    sku: "RJ-NCK-028",
    netWeight: 10.72,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-29",
    name: "Floral Charm Necklace Set",
    image: "/images/products/necklaces/gold-necklace-25.png",

    images: ["/images/products/necklaces/gold-necklace-25.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "floral-charm-necklace-set",
    sku: "RJ-NCK-029",
    netWeight: 10.98,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-30",
    name: "Elegant Heritage Necklace",
    image: "/images/products/necklaces/gold-necklace-26.png",

    images: ["/images/products/necklaces/gold-necklace-26.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "elegant-heritage-necklace",
    sku: "RJ-NCK-030",
    netWeight: 9.44,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-31",
    name: "Antique Necklace Set",
    image: "/images/products/necklaces/gold-necklace-27.png",

    images: ["/images/products/necklaces/gold-necklace-27.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "antique-necklace-set",
    sku: "RJ-NCK-031",
    netWeight: 10.7,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-32",
    name: "Traditional Gold Necklace",
    image: "/images/products/necklaces/gold-necklace-28.png",

    images: ["/images/products/necklaces/gold-necklace-28.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "traditional-gold-necklacet",
    sku: "RJ-NCK-032",
    netWeight: 9.44,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-33",
    name: "Graceful Pendant Necklace",
    image: "/images/products/necklaces/gold-necklace-29.png",

    images: ["/images/products/necklaces/gold-necklace-29.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "graceful-pendant-necklace",
    sku: "RJ-NCK-033",
    netWeight: 11.27,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-34",
    name: "Vintage Necklace Set",
    image: "/images/products/necklaces/gold-necklace-30.png",

    images: ["/images/products/necklaces/gold-necklace-30.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "vintage-temple-necklace",
    sku: "RJ-NCK-034",
    netWeight: 9.44,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-35",
    name: "Divine Lotus Necklace",
    image: "/images/products/necklaces/gold-necklace-31.png",

    images: ["/images/products/necklaces/gold-necklace-31.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "divine-lotus-necklace",
    sku: "RJ-NCK-035",
    netWeight: 18.06,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-36",
    name: "Imperial Gold Necklace",
    image: "/images/products/necklaces/gold-necklace-32.png",

    images: ["/images/products/necklaces/gold-necklace-32.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "imperial-gold-necklace",
    sku: "RJ-NCK-036",
    netWeight: 17.08,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-37",
    name: "Royal Bloom Necklace",
    image: "/images/products/necklaces/gold-necklace-33.png",

    images: ["/images/products/necklaces/gold-necklace-33.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "royal-bloom-necklace",
   sku: "RJ-NCK-037",
    netWeight: 16.22,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-38",
    name: "Heritage Floral Necklace",
    image: "/images/products/necklaces/gold-necklace-34.png",

    images: ["/images/products/necklaces/gold-necklace-34.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "heritage-floral-necklace",
    sku: "RJ-NCK-038",
    netWeight: 17.95,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
  {
    id: "p-39",
    name: "Heritage Floral Necklace",
    image: "/images/products/necklaces/gold-necklace-35.png",

    images: ["/images/products/necklaces/gold-necklace-35.png"],
    metal: "Gold",
    category: "Necklaces",
    purity: "18K",
    currentPrice: 79200,
    slug: "heritage-floral-necklace-2",
    sku: "RJ-NCK-039",
    netWeight: 14.18,
    goldRate: 6500,
    makingCharges: 8600,
    stoneCharges: 18500,
    avgRating: 4.8,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: false,
  },
    
  {
    id: "p-40",
    name: "Temple Gold Bangles Set",
    image:
      "https://i.pinimg.com/736x/1f/40/e6/1f40e696a609011036fa95e608ba5672.jpg",
    images: [
      "https://i.pinimg.com/736x/1f/40/e6/1f40e696a609011036fa95e608ba5672.jpg",
    ],
    metal: "Gold",
    category: "Bangles",
    purity: "22K",
    currentPrice: 62000,
    slug: "temple-gold-bangles",
    sku: "RJ0001",
    netWeight: 18,
    goldRate: 6500,
    makingCharges: 5000,
    stoneCharges: 3000,
    avgRating: 4.6,
    reviewCount: 18,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "p-41",
    name: "22K Gold Chain",
    image:
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/764/1780054045_2efbce9def7e01b07340.webp",
    images: [
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/764/1780054045_2efbce9def7e01b07340.webp",
    ],
    metal: "Gold",
    category: "Chains",
    purity: "22K",
    currentPrice: 35000,
    slug: "22k-gold-chain",
    sku: "RJ0002",
    netWeight: 10,
    goldRate: 6500,
    makingCharges: 2200,
    stoneCharges: 0,
    avgRating: 4.3,
    reviewCount: 14,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  


  {
    id: "p-42",
    name: "Silver Pendant Plates",
    image:
      "https://tiimg.tistatic.com/fp/1/006/590/fine-finished-brass-pooja-thali-023.jpg",
    images: [
      "https://tiimg.tistatic.com/fp/1/006/590/fine-finished-brass-pooja-thali-023.jpg",
    ],
    metal: "Silver",
    category: "Pendants",
    purity: "24K",
    currentPrice: 12000,
    slug: "silver-pendant",
    sku: "RJ0003",
    netWeight: 5,
    goldRate: 6500,
    makingCharges: 1000,
    stoneCharges: 0,
    avgRating: 4.1,
    reviewCount: 8,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },
  
  {
    id: "p-43",
    name: "Ruby Mangalsutra",
    image:
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1164/1662631757_9cbff375c83181ab33e4.png",
    images: [
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1164/1662631757_9cbff375c83181ab33e4.png",
    ],
    metal: "Gold",
    category: "Mangalsutras",
    purity: "22K",
    currentPrice: 42000,
    slug: "ruby-mangalsutra",
    sku: "RJ0004",
    netWeight: 11,
    goldRate: 6500,
    makingCharges: 3000,
    stoneCharges: 5000,
    avgRating: 4.7,
    reviewCount: 22,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
    {
    id: "p-44",
    name: "Open Cuff Gold Bracelet",
    image:
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1704/1780137941_828a35a21f49303c9344.webp",
    images: [
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1704/1780137941_828a35a21f49303c9344.webp",
    ],
    metal: "Gold",
    category: "Bracelets",
    purity: "22K",
    currentPrice: 39000,
    slug: "open-cuff-gold-bracelet",
    sku: "RJ0005",
    netWeight: 9,
    goldRate: 6500,
    makingCharges: 2600,
    stoneCharges: 0,
    avgRating: 4.2,
    reviewCount: 11,
    inStock: true,
    isFeatured: false,
    isTrending: false,
  },
  {
    id: "p-45",
    name: "Mangalsutra Pendant Chain",
    image:
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1404/1780053072_2e61ea8ef659a5e4db1f.webp",
    images: [
      "https://d25g9z9s77rn4i.cloudfront.net/uploads/product/1404/1780053072_2e61ea8ef659a5e4db1f.webp",
    ],
    metal: "Gold",
    category: "Chains",
    purity: "22K",
    currentPrice: 31000,
    slug: "mangalsutra-pendant-chain",
    sku: "RJ0006",
    netWeight: 8,
    goldRate: 6500,
    makingCharges: 2400,
    stoneCharges: 3000,
    avgRating: 4.4,
    reviewCount: 15,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  
  {
    id: "p-46",
    name: "Minimal Heart Pendant Necklace",
    image:
      "https://i.pinimg.com/736x/d0/bd/b7/d0bdb7e5cfd56c801ed218286eebf994.jpg",
    images: [
      "https://i.pinimg.com/736x/d0/bd/b7/d0bdb7e5cfd56c801ed218286eebf994.jpg",
    ],
    metal: "Gold",
    category: "Pendants",
    purity: "18K",
    currentPrice: 18500,
    slug: "minimal-heart-pendant-necklace",
    sku: "RJ0007",
    netWeight: 5,
    goldRate: 6500,
    makingCharges: 2200,
    stoneCharges: 0,
    avgRating: 4.7,
    reviewCount: 24,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "p-47",
    name: "Classic Heart Charm Necklace",
    image:
      "https://i.pinimg.com/736x/4f/92/06/4f9206b10dbeed57bc5493e1ac6956d7.jpg",
    images: [
      "https://i.pinimg.com/736x/4f/92/06/4f9206b10dbeed57bc5493e1ac6956d7.jpg",
    ],
    metal: "Gold",
    category: "Pendants",
    purity: "18K",
    currentPrice: 21200,
    slug: "classic-heart-charm-necklace",
   sku: "RJ0008",
    netWeight: 6,
    goldRate: 6500,
    makingCharges: 2500,
    stoneCharges: 0,
    avgRating: 4.8,
    reviewCount: 31,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-48",
    name: "Little Heart Snake Chain Necklace",
    image:
      "https://i.pinimg.com/736x/23/24/60/232460f702f5ea64e9ec67efe7b26b80.jpg",
    images: [
      "https://i.pinimg.com/736x/23/24/60/232460f702f5ea64e9ec67efe7b26b80.jpg",
    ],
    metal: "Gold",
    category: "Pendants",
    purity: "18K",
    currentPrice: 23800,
    slug: "little-heart-snake-chain-necklace",
    sku: "RJ0009",
    netWeight: 7,
    goldRate: 6500,
    makingCharges: 3200,
    stoneCharges: 0,
    avgRating: 4.9,
    reviewCount: 42,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-49",
    name: "Figaro Chain Heart Necklace",
    image:
      "https://i.pinimg.com/1200x/71/20/bd/7120bd8e3f62a0195463bfe3773bfac5.jpg",
    images: [
      "https://i.pinimg.com/1200x/71/20/bd/7120bd8e3f62a0195463bfe3773bfac5.jpg",
    ],
    metal: "Gold",
    category: "Chains",
    purity: "18K",
    currentPrice: 27500,
    slug: "figaro-chain-heart-necklace",
    sku: "RJ0010",
    netWeight: 8,
    goldRate: 6500,
    makingCharges: 3600,
    stoneCharges: 0,
    avgRating: 4.6,
    reviewCount: 19,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "p-50",
    name: "Sweet Hollow Heart Pendant Necklace",
    image:
      "https://i.pinimg.com/1200x/12/6c/c0/126cc0453507708eca14a2e0acc7c570.jpg",
    images: [
      "https://i.pinimg.com/1200x/12/6c/c0/126cc0453507708eca14a2e0acc7c570.jpg",
    ],
    metal: "Gold",
    category: "Pendants",
    purity: "18K",
    currentPrice: 19800,
    slug: "sweet-hollow-heart-pendant-necklace",
    sku: "RJ0011",
    netWeight: 5,
    goldRate: 6500,
    makingCharges: 2400,
    stoneCharges: 0,
    avgRating: 4.7,
    reviewCount: 27,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "p-51",
    name: "Silver Open Heart Pendant Necklace",
    image:
      "https://i.pinimg.com/1200x/dd/cd/03/ddcd032172acc1c0391f283f6bad9730.jpg",
    images: [
      "https://i.pinimg.com/1200x/dd/cd/03/ddcd032172acc1c0391f283f6bad9730.jpg",
    ],
    metal: "Silver",
    category: "Pendants",
    purity: "925 Sterling Silver",
    currentPrice: 4200,
    slug: "silver-open-heart-pendant-necklace",
   sku: "RJ0012",
    netWeight: 4,
    goldRate: 0,
    makingCharges: 800,
    stoneCharges: 0,
    avgRating: 4.7,
    reviewCount: 22,
    inStock: true,
    isFeatured: false,
    isTrending: true,
  },
  {
    id: "p-52",
    name: "Blue Floral Crystal Pendant Necklace",
    image:
      "https://i.pinimg.com/1200x/53/4b/0b/534b0ba314b5f917df82352fc343e49d.jpg",
    images: [
      "https://i.pinimg.com/1200x/53/4b/0b/534b0ba314b5f917df82352fc343e49d.jpg",
    ],
    metal: "Silver",
    category: "Pendants",
    purity: "925 Sterling Silver",
    currentPrice: 6800,
    slug: "blue-floral-crystal-pendant-necklace",
    sku: "RJ0013",
    netWeight: 6,
    goldRate: 0,
    makingCharges: 1200,
    stoneCharges: 2500,
    avgRating: 4.9,
    reviewCount: 37,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  
  {
    id: "p-53",
    name: "Celestia Diamond Bracelet",
    image:
      "https://i.pinimg.com/1200x/71/e7/14/71e714fe510c7375d5b550ccbd4cfcb0.jpg",
    images: [
      "https://i.pinimg.com/1200x/71/e7/14/71e714fe510c7375d5b550ccbd4cfcb0.jpg",
    ],
    metal: "Gold",
    category: "Bracelets",
    purity: "18K",
    currentPrice: 48500,
    slug: "celestia-diamond-bracelet",
   sku: "RJ0014",
    netWeight: 8,
    goldRate: 6500,
    makingCharges: 4500,
    stoneCharges: 12000,
    avgRating: 4.9,
    reviewCount: 42,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-54",
    name: "Aurora Leaf Diamond Bracelet",
    image:
      "https://i.pinimg.com/1200x/a4/53/c7/a453c795b32413f7acd45d0a6ff87ce9.jpg",
    images: [
      "https://i.pinimg.com/1200x/a4/53/c7/a453c795b32413f7acd45d0a6ff87ce9.jpg",
    ],
    metal: "Gold",
    category: "Bracelets",
    purity: "18K",
    currentPrice: 52800,
    slug: "aurora-leaf-diamond-bracelet",
    sku: "RJ0015",
    netWeight: 9,
    goldRate: 6500,
    makingCharges: 5200,
    stoneCharges: 14500,
    avgRating: 4.8,
    reviewCount: 38,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    id: "p-55",
    name: "Royal Filigree Diamond Bangle",
    image:
      "https://i.pinimg.com/736x/cd/27/89/cd27898d9feac58b30197be005befa91.jpg",
    images: [
      "https://i.pinimg.com/736x/cd/27/89/cd27898d9feac58b30197be005befa91.jpg",
    ],
    metal: "Gold",
    category: "Bangles",
    purity: "22K",
    currentPrice: 89500,
    slug: "royal-filigree-diamond-bangle",
    sku: "RJ0016",
    netWeight: 15,
    goldRate: 6500,
    makingCharges: 9500,
    stoneCharges: 18000,
    avgRating: 5.0,
    reviewCount: 27,
    inStock: true,
    isFeatured: true,
    isTrending: true,
  },

  {
    id: "p-56",
    name: "Gold Bangles",
    slug: "product-3",
    sku: "RJ0017",
    image:
      "https://i.pinimg.com/736x/82/6c/0f/826c0f20bcff3dc6a1026a353c266676.jpg",
    images: [
      "https://i.pinimg.com/736x/82/6c/0f/826c0f20bcff3dc6a1026a353c266676.jpg",
    ],
    metal: "Gold",
    purity: "22KT",
    netWeight: 20.5,
    currentPrice: 102000,
    goldRate: 6500,
    makingCharges: 4000,
    stoneCharges: 5000,
    avgRating: 4.8,
    reviewCount: 87,
    inStock: true,
    isFeatured: false,
    isTrending: true,
    category: "Bangles",
  },
 
];
