import { Router } from 'express';
import { createInvoice, getInvoices, getInvoiceById, resendWhatsApp, getGSTSummary } from '../controllers/invoiceController';
import { authenticate, authorize } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/', getInvoices);
router.post('/', authorize('ADMIN','SUPER_ADMIN','STORE_MANAGER','SALES_STAFF'), createInvoice);
router.get('/gst-summary', authorize('ADMIN','SUPER_ADMIN','STORE_MANAGER'), getGSTSummary);
router.get('/:id', getInvoiceById);
router.post('/:id/resend-whatsapp', resendWhatsApp);
export default router;
